[profile.release]
lto = true
opt-level = "s"
panic = "abort"

[workspace]
members = [
    "testing-process",
    "test/testing-process-test/testing-process-test",
    "target/caller-utils",
]
resolver = "2"
